/*
  data.js
  Single source of truth for all recipe content on the site.
  Every other script reads from this array — nothing is hard-coded twice.
*/

const RECIPES = [
  {
    id: "rolex",
    title: "Rolex (Rolled Chapati & Egg)",
    image: "https://static01.nyt.com/images/2023/04/14/multimedia/14KOMOLAFE-rex2-rolex-zkfc-copy/14KOMOLAFE-rex2-rolex-zkfc-superJumbo.jpg?format=pjpg&quality=75&auto=webp&disable=upscale",
    alt: "A Ugandan rolex — a chapati rolled around a vegetable omelette, sliced in half on a plate",
    cuisine: "Ugandan",
    mealType: "Breakfast",
    diet: "Vegetarian",
    prepTime: 15,
    difficulty: "Easy",
    calories: 380,
    servings: 1,
    description: "Uganda's favorite street food, easy enough for any weekday morning: a spiced vegetable omelette rolled up inside a warm chapati.",
    ingredients: [
      "2 chapatis (store-bought or homemade)",
      "3 eggs",
      "1 small tomato, diced",
      "1 small onion, diced",
      "1/2 cup shredded cabbage",
      "1 green chili, minced (optional)",
      "1 tbsp cooking oil",
      "Salt and black pepper, to taste"
    ],
    steps: [
      { text: "Whisk the eggs in a bowl or mug and stir/whisk in the tomato, onion, cabbage, chili, salt, and pepper.", image: "https://globaltableadventure.com/wp-content/uploads/2015/06/how-to-make-rolex-from-uganda.jpg", alt: "" },
      { text: "Heat the oil in a flat pan over medium heat and pour in the egg mixture, spreading it into a thin layer like an omelette.", image: "https://globaltableadventure.com/wp-content/uploads/2015/06/ugandan-rolex-recipe-12.jpg", alt: "" },
      { text: "When the first side of the egg is cooked flip the egg, lay a warmed chapati directly on top and press gently.", image: "https://globaltableadventure.com/wp-content/uploads/2015/06/ugandan-rolex-recipe-01-1200x800.jpg", alt: "" },
      { text: "Flip the whole stack and cook for another minute so the chapati warms through.", image: "", alt: "" },
      { text: "Repeat with the second chapati and remaining egg if making two rolls.", image: "", alt: "" },
      { text: "Remove from the pan, roll tightly while warm, and slice in half to serve.", image: "https://seemagetsbaked.com/wp-content/uploads/2024/10/ROLEX-768x1365.jpg", alt: "" }
    ],
    tags: ["street-food", "quick", "breakfast"]
  },
  {
    id: "katogo",
    title: "Katogo (Matooke & Bean Stew)",
    image: "https://akitcheninuganda.com/wp-content/uploads/2018/06/katogo-akitchen-in-uganda-4.jpg?w=1312",
    alt: "A bowl of katogo — mashed green banana simmered with beans, onion, and tomato",
    cuisine: "Ugandan",
    mealType: "Lunch",
    diet: "Vegan",
    prepTime: 35,
    difficulty: "Medium",
    calories: 420,
    servings: 4,
    description: "A one-pot Ugandan staple that turns green bananas (matoke) and beans into a hearty, filling stew — traditionally eaten for breakfast or lunch.",
    ingredients: [
      "6 green bananas (matoke), peeled and chopped",
      "2 cups cooked red beans (or 1 can, drained and rinsed)",
      "1 onion, diced",
      "2 tomatoes, chopped",
      "2 cloves garlic, minced",
      "2 tbsp cooking oil",
      "1 vegetable stock cube",
      "2 tbsp chopped coriander",
      "Salt, to taste",
      "Water, as needed"
    ],
    steps: [
      { text: "Place the peeled, chopped matoke in a pot, cover with water, and boil for 20 minutes until tender.", image: "https://www.aljazeera.com/wp-content/uploads/2022/05/Peeled-Green-Bananas.jpeg?w=770&resize=770%2C513&quality=80", alt: "Freshly peeled green bananas." },
      { text: "In a separate pan, heat the oil and sauté the onion until soft, about 4 minutes.", image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjHMSM_iZjVM4sgnjRBSuJDaLiHf_ZRCw4mVbsIYFXr02Ferv0Nn948S5Kk5_PF0-4zp6f_L-3FL5DA44RC_157gks6-K-RVTmpHcIXww4xO0egPrckyiWesARFQH1HWNiVrmsu6e_pH1Q/s1600/IMG_2686.JPG", alt: "" },
      { text: "Add the garlic and tomatoes and cook until the tomatoes break down, about 5 minutes.", image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjudyQLr0LHtC7LN6XxUqfC6oF5Eos0rhP4wVPArj2ToS1UZt5Ub7H-4Qva6iD2LXP8sD8N-ifoaxjP1sFu6RXx1FojIBjMR_NfVfVLis8t3msZ00foNkwugJSnbPevti0sZpE6pifVqmo/s1600/IMG_2688.jpg", alt: "" },
      { text: "Drain the matoke and lightly mash it, leaving some texture.", image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiH05luaYrrObYh0hA4n1QJB9jtBEOrvUtm8v8SyOihMI-e9uHZbpy9CQWBSMIAcVOR3ikGizzu5jWiIVz7AS6MhpIW_l5MU4k6VTqeq4PnO0thcTQat8-r5jhH7pwXjH5gNuvWGK-ZvWg/s1600/IMG_2694.jpg", alt: "" },
      { text: "Stir the matoke and cooked beans into the tomato mixture along with the stock cube and a splash of water.", image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiH05luaYrrObYh0hA4n1QJB9jtBEOrvUtm8v8SyOihMI-e9uHZbpy9CQWBSMIAcVOR3ikGizzu5jWiIVz7AS6MhpIW_l5MU4k6VTqeq4PnO0thcTQat8-r5jhH7pwXjH5gNuvWGK-ZvWg/s320/IMG_2694.jpg", alt: "" },
      { text: "Simmer for 10 minutes, season with salt, and finish with chopped coriander.", image: "https://www.aljazeera.com/wp-content/uploads/2022/05/Irish-Sweet-Potato-Yams-and-Beans-katogo-1.jpg?resize=770%2C513&quality=80", alt: "Served hot" }
    ],
    tags: ["one-pot", "staple", "plant-based"]
  },
  {
    id: "kachumbari",
    title: "Kachumbari (Tomato & Onion Salad)",
    image: "https://images.pexels.com/photos/27583283/pexels-photo-27583283.jpeg",
    alt: "A fresh salad of diced tomato, onion, and cilantro in a bowl with lime wedges",
    cuisine: "East African",
    mealType: "Lunch",
    diet: "Vegan",
    prepTime: 10,
    difficulty: "Easy",
    calories: 60,
    servings: 4,
    description: "A crisp, no-cook side salad found across East Africa. Bright, sharp, and quick enough to make while everything else is still cooking.",
    ingredients: [
      "3 tomatoes, diced",
      "1 red onion, thinly sliced",
      "1/2 cucumber, diced",
      "1 green chili, minced (optional)",
      "2 tbsp chopped cilantro",
      "1 lime, juiced",
      "Salt, to taste"
    ],
    steps: [
      { text: "Combine the tomato, onion, cucumber, and chili in a bowl.", image: "https://images.pexels.com/photos/7223295/pexels-photo-7223295.jpeg", alt: "" },
      { text: "Rinse the sliced onion under cold water first if you prefer a milder bite.", image: "https://images.pexels.com/photos/36895504/pexels-photo-36895504.jpeg", alt: "" },
      { text: "Add the cilantro and lime juice, then toss gently.", image: "https://images.pexels.com/photos/8378101/pexels-photo-8378101.jpeg", alt: "" },
      { text: "Season with salt and let it sit for 5 minutes before serving so the flavors combine.", image: "https://images.pexels.com/photos/27583283/pexels-photo-27583283.jpeg", alt: "" }
    ],
    tags: ["no-cook", "side-dish", "quick"]
  },
  {
    id: "jollof-rice",
    title: "Jollof Rice with Vegetables",
    image: "https://img.sndimg.com/food/image/upload/f_auto,c_thumb,q_55,w_744,ar_5:4/v1/img/recipes/44/54/47/UkXwrHEdQ7GY9oWZnRk3_authentic-west-african-jollof-rice-3447.jpg",
    alt: "A pot of red-orange jollof rice studded with carrots, peas, and green beans",
    cuisine: "West African",
    mealType: "Dinner",
    diet: "Vegan",
    prepTime: 40,
    difficulty: "Medium",
    calories: 480,
    servings: 4,
    description: "West Africa's iconic one-pot rice, built on a blended tomato-pepper base and warmed through with thyme and curry powder.",
    ingredients: [
      "2 cups long-grain rice, rinsed",
      "3 tomatoes",
      "1 red bell pepper",
      "1 onion",
      "2 cloves garlic",
      "1-inch piece ginger",
      "2 tbsp tomato paste",
      "3 cups vegetable stock",
      "1 cup mixed vegetables (carrot, peas, green beans)",
      "1 tsp curry powder",
      "1 tsp dried thyme",
      "1 bay leaf",
      "3 tbsp cooking oil",
      "Salt, to taste"
    ],
    steps: [
      { text: "Blend the tomatoes, bell pepper, half the onion, garlic, and ginger into a smooth puree.", image: "https://www.dashofjazz.com/wp-content/uploads/2024/03/Dash-of-Jazz-Vegetable-Puree-for-Jollof-Rice-1152x1536.jpg", alt: "" },
      { text: "Dice the remaining onion and sauté it in the oil until soft, about 4 minutes.", image: "https://images.pexels.com/photos/6550435/pexels-photo-6550435.jpeg", alt: "" },
      { text: "Stir in the tomato paste and cook for 2 minutes, then add the blended puree.", image: "", alt: "" },
      { text: "Simmer the puree for 10 to 12 minutes, stirring occasionally, until it darkens and thickens.", image: "", alt: "" },
      { text: "Add the curry powder, thyme, bay leaf, and stock, then bring to a boil.", image: "https://www.dashofjazz.com/wp-content/uploads/2024/03/Dash-of-Jazz-Best-Nigerian-Jollof-Rice-4-1024x1536.jpg", alt: "" },
      { text: "Stir in the rice and mixed vegetables, cover, reduce heat to low, and cook for 20 to 25 minutes until the rice is tender and the liquid is absorbed.", image: "https://images.pexels.com/photos/16563083/pexels-photo-16563083.jpeg", alt: "" }
    ],
    tags: ["one-pot", "plant-based", "gluten-free"]
  },
  {
    id: "misir-wot",
    title: "Misir Wot (Ethiopian Red Lentil Stew)",
    image: "https://www.daringgourmet.com/wp-content/uploads/2018/04/Misir-Wat-3-cropped.jpg",
    alt: "A bowl of deep red Ethiopian lentil stew garnished with fresh herbs",
    cuisine: "Ethiopian",
    mealType: "Dinner",
    diet: "Vegan",
    prepTime: 30,
    difficulty: "Easy",
    calories: 340,
    servings: 4,
    description: "A warming, protein-packed lentil stew built on caramelized onions and berbere spice — a staple of Ethiopian home cooking.",
    ingredients: [
      "1 1/2 cups split red lentils, rinsed",
      "1 large onion, finely diced",
      "3 cloves garlic, minced",
      "1 tbsp grated ginger",
      "2 tbsp berbere spice blend",
      "2 tbsp tomato paste",
      "3 tbsp cooking oil",
      "3 cups water",
      "Salt, to taste"
    ],
    steps: [
      { text: "Heat the oil in a pot and cook the onion over medium heat until deeply golden, about 10 minutes.", image: "https://thatgreenlyfe.com/wp-content/uploads/2021/01/Ethiopian-Red-Lentil-Stew-9-recipe-courtesy-of-That-Green-Lyfe.jpg", alt: "" },
      { text: "Add the garlic and ginger and cook for 1 minute until fragrant.", image: "https://thatgreenlyfe.com/wp-content/uploads/2021/01/Ethiopian-Red-Lentil-Stew-10-recipe-courtesy-of-That-Green-Lyfe.jpg", alt: "" },
      { text: "Stir in the berbere spice and tomato paste and cook for 2 minutes.", image: "https://thatgreenlyfe.com/wp-content/uploads/2021/01/Ethiopian-Red-Lentil-Stew-2-recipe-courtesy-of-That-Green-Lyfe.jpg", alt: "" },
      { text: "Add the lentils and water, then bring to a boil.", image: "https://thatgreenlyfe.com/wp-content/uploads/2021/01/Ethiopian-Red-Lentil-Stew-5-recipe-courtesy-of-That-Green-Lyfe-Copy.jpg", alt: "" },
      { text: "Reduce the heat and simmer for 15 to 18 minutes, stirring occasionally, until the lentils are soft and the stew has thickened.", image: "https://thatgreenlyfe.com/wp-content/uploads/2021/01/Ethiopian-Red-Lentil-Stew-11-recipe-courtesy-of-That-Green-Lyfe.jpg", alt: "" },
      { text: "Season with salt and serve with injera or flatbread.", image: "https://thatgreenlyfe.com/wp-content/uploads/2021/01/Ethiopian-Red-Lentil-Stew-13-recipe-courtesy-of-That-Green-Lyfe.jpg", alt: "" }
    ],
    tags: ["plant-based", "gluten-free", "spiced"]
  },
  {
    id: "sukuma-wiki",
    title: "Sukuma Wiki (Braised Collard Greens)",
    image: "https://eatwellabi.com/wp-content/uploads/2023/02/sukuma-wiki-16.jpg",
    alt: "A pan of braised collard greens with onion and tomato, served as a side dish",
    cuisine: "East African",
    mealType: "Lunch",
    diet: "Vegan",
    prepTime: 15,
    difficulty: "Easy",
    calories: 120,
    servings: 4,
    description: "A quick, everyday green found on tables across Kenya and Uganda — its name means \"stretch the week,\" because it turns a few leaves into a real side dish.",
    ingredients: [
      "1 bunch collard greens (or kale), thinly sliced",
      "1 onion, diced",
      "1 tomato, chopped",
      "2 cloves garlic, minced",
      "2 tbsp cooking oil",
      "1/2 vegetable stock cube",
      "Salt and black pepper, to taste"
    ],
    steps: [
      { text: "Heat the oil in a wide pan and sauté the onion until soft, about 4 minutes.", image: "https://eatwellabi.com/wp-content/uploads/2023/01/sukuma-wiki-3-720x480.jpg", alt: "" },
      { text: "Add the garlic and tomato and cook until the tomato softens, about 3 minutes.", image: "https://eatwellabi.com/wp-content/uploads/2023/01/sukuma-wiki-3-720x480.jpg", alt: "" },
      { text: "Add the sliced greens in batches, stirring until each addition wilts down.", image: "https://eatwellabi.com/wp-content/uploads/2023/01/sukuma-wiki-5-720x480.jpg", alt: "" },
      { text: "Crumble in the stock cube, season with salt and pepper, and cook for 5 more minutes until tender.", image: "https://eatwellabi.com/wp-content/uploads/2023/01/sukuma-wiki-6-720x480.jpg", alt: "" }
    ],
    tags: ["side-dish", "quick", "gluten-free"]
  },
  {
    id: "pilau-rice",
    title: "Pilau Rice with Chicken",
    image: "https://salmasrecipes.com/wp-content/uploads/2020/05/chicken-pilau-directions-40-1024x785.jpg",
    alt: "A pot of spiced pilau rice with chicken pieces and potatoes",
    cuisine: "East African",
    mealType: "Dinner",
    diet: "None",
    prepTime: 45,
    difficulty: "Medium",
    calories: 560,
    servings: 4,
    description: "Fragrant, whole-spice rice cooked with chicken and potatoes in one pot — a Swahili-coast classic that's just as popular across East Africa.",
    ingredients: [
      "2 cups basmati rice, rinsed",
      "4 chicken thighs, bone-in",
      "1 onion, sliced",
      "3 cloves garlic, minced",
      "1-inch piece ginger, grated",
      "2 potatoes, cubed",
      "1 tsp cumin seeds",
      "4 cardamom pods",
      "1 cinnamon stick",
      "4 whole cloves",
      "3 cups chicken stock",
      "3 tbsp cooking oil",
      "Salt, to taste"
    ],
    steps: [
      { text: "Heat the oil in a large pot and brown the chicken thighs on both sides. Remove and set aside.", image: "https://salmasrecipes.com/wp-content/uploads/2020/05/chicken-pilau-directions-11-1024x1024.jpg", alt: "" },
      { text: "In the same pot, add the cumin seeds, cardamom, cinnamon, and cloves, and toast for 30 seconds until fragrant.", image: "https://salmasrecipes.com/wp-content/uploads/2020/05/chicken-pilau-directions-9-1024x1002.jpg", alt: "" },
      { text: "Add the onion and cook until golden, about 6 minutes.", image: "https://salmasrecipes.com/wp-content/uploads/2020/05/chicken-pilau-directions-6-1024x982.jpg", alt: "" },
      { text: "Stir in the garlic and ginger and cook for 1 minute.", image: "https://salmasrecipes.com/wp-content/uploads/2020/05/chicken-pilau-directions-10-1024x1006.jpg", alt: "" },
      { text: "Return the chicken to the pot along with the potatoes, rice, and stock.", image: "https://salmasrecipes.com/wp-content/uploads/2020/05/chicken-pilau-directions-35-982x1024.jpg", alt: "" },
      { text: "Bring to a boil, then cover, reduce the heat to low, and cook for 20 to 25 minutes until the rice is tender and the chicken is cooked through.", image: "https://salmasrecipes.com/wp-content/uploads/2020/05/chicken-pilau-directions-39-958x1024.jpg", alt: "" }
    ],
    tags: ["one-pot", "family-dinner", "spiced"]
  },
  {
    id: "shakshuka",
    title: "Shakshuka (Eggs in Spiced Tomato Sauce)",
    image: "https://danastable.com/wp-content/uploads/2025/08/Shakshuka-hero1-1152x1536.jpg",
    alt: "A cast iron pan of shakshuka — eggs poached in a spiced tomato and pepper sauce, garnished with herbs",
    cuisine: "North African",
    mealType: "Breakfast",
    diet: "Vegetarian",
    prepTime: 25,
    difficulty: "Easy",
    calories: 320,
    servings: 2,
    description: "A North African breakfast classic: eggs gently poached in a garlicky, spiced tomato and pepper sauce, mopped up with warm bread.",
    ingredients: [
      "2 tbsp olive oil",
      "1 onion, diced",
      "1 red bell pepper, diced",
      "3 cloves garlic, minced",
      "1 tsp cumin",
      "1 tsp paprika",
      "1/4 tsp cayenne pepper (optional)",
      "1 can (14 oz) crushed tomatoes",
      "4 eggs",
      "2 tbsp chopped parsley or cilantro",
      "Salt and black pepper, to taste",
      "Crusty bread, for serving"
    ],
    steps: [
      { text: "Heat the olive oil in a wide skillet and sauté the onion and bell pepper until soft, about 5 minutes.", image: "https://danastable.com/wp-content/uploads/2025/08/Shakshuka-Process-shot1-saute-1152x1536.jpg", alt: "" },
      { text: "Stir in the garlic, cumin, paprika, and cayenne and cook for 1 minute until fragrant.", image: "https://danastable.com/wp-content/uploads/2025/08/Shakshuka-Process-shot1-saute-1152x1536.jpg", alt: "" },
      { text: "Add the crushed tomatoes, season with salt and pepper, and simmer for 10 minutes until slightly thickened.", image: "https://danastable.com/wp-content/uploads/2025/08/Shakshuka-Process-shot2-CookSauce-1152x1536.jpg", alt: "" },
      { text: "Use a spoon to make four small wells in the sauce and crack an egg into each one.", image: "https://danastable.com/wp-content/uploads/2025/08/Shakshuka-Process-shot5-AddEggs-1152x1536.jpg", alt: "" },
      { text: "Cover the pan and cook for 5 to 8 minutes, until the egg whites are set but the yolks are still soft.", image: "https://danastable.com/wp-content/uploads/2025/08/Shakshuka-Process-shot6-CookEggs-1152x1536.jpg", alt: "" },
      { text: "Garnish with fresh herbs and serve straight from the pan with crusty bread.", image: "https://danastable.com/wp-content/uploads/2025/08/Shakshuka-hero2-1152x1536.jpg", alt: "" }
    ],
    tags: ["breakfast", "vegetarian", "one-pan"]
  },
  {
    id: "chicken-yassa",
    title: "Chicken Yassa (Senegalese Lemon Chicken)",
    image: "https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_1024/https://icancookthat.org/wp-content/uploads/2017/03/IMG_80281-1024x683.jpg",
    alt: "Chicken thighs braised with caramelized onions and lemon, served over rice",
    cuisine: "West African",
    mealType: "Dinner",
    diet: "Gluten-Free",
    prepTime: 45,
    difficulty: "Medium",
    calories: 480,
    servings: 4,
    description: "A tangy, onion-heavy Senegalese classic — chicken marinated in lemon and mustard, then braised with a mountain of slow-cooked onions.",
    ingredients: [
      "4 chicken thighs",
      "3 onions, thinly sliced",
      "2 lemons, juiced",
      "2 tbsp Dijon mustard",
      "3 cloves garlic, minced",
      "1 scotch bonnet or chili, pricked whole (optional)",
      "3 tbsp cooking oil",
      "1 bay leaf",
      "1/2 cup water or chicken stock",
      "Salt and black pepper, to taste",
      "Cooked rice, for serving"
    ],
    steps: [
      { text: "In a bowl, combine the lemon juice, mustard, garlic, salt, and pepper. Add the chicken and half the sliced onions, and marinate for at least 30 minutes (or up to overnight in the fridge).", image: "https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_768/https://icancookthat.org/wp-content/uploads/2017/03/IMG_8012-2-768x768.jpg", alt: "" },
      { text: "Remove the chicken from the marinade, reserving the liquid and onions separately.", image: "https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_768/https://icancookthat.org/wp-content/uploads/2017/03/IMG_8014-1-768x768.jpg", alt: "" },
      { text: "Heat the oil in a pot and sear the chicken on both sides until browned. Remove and set aside.", image: "https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_768/https://icancookthat.org/wp-content/uploads/2017/03/IMG_8019-768x768.jpg", alt: "" },
      { text: "Add all the onions to the pot and cook over medium-low heat for 15 to 20 minutes, stirring occasionally, until soft and golden.", image: "https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_768/https://icancookthat.org/wp-content/uploads/2017/03/IMG_8016-768x768.jpg", alt: "" },
      { text: "Return the chicken to the pot with the reserved marinade, bay leaf, chili, and water.", image: "https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_768/https://icancookthat.org/wp-content/uploads/2017/03/IMG_8020-768x768.jpg", alt: "" },
      { text: "Cover and simmer for 20 minutes, until the chicken is cooked through. Serve over rice.", image: "https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_1024/https://icancookthat.org/wp-content/uploads/2017/03/IMG_80321-1-1024x683.jpg", alt: "" }
    ],
    tags: ["braised", "family-dinner", "gluten-free"]
  },
  {
    id: "pondu",
    title: "Pondu (Cassava Leaf & Peanut Stew)",
    image: "https://cookingwithclaudy.com/wp-content/uploads/2023/11/20231103121607_IMG_6445.jpg",
    alt: "A pot of dark green cassava leaf stew simmered in a peanut sauce",
    cuisine: "Central African",
    mealType: "Dinner",
    diet: "Vegan",
    prepTime: 35,
    difficulty: "Medium",
    calories: 400,
    servings: 4,
    description: "A Congolese staple traditionally made with pounded cassava leaves in a rich peanut sauce. This version uses collard greens or spinach, which are easier to find outside Central Africa.",
    ingredients: [
      "4 cups finely chopped collard greens or spinach (or cassava leaves, if available)",
      "1 onion, diced",
      "2 cloves garlic, minced",
      "1 tomato, chopped",
      "1/2 cup natural peanut butter, unsweetened",
      "2 tbsp cooking oil",
      "1 small eggplant, cubed (optional)",
      "1 vegetable stock cube",
      "1 chili, minced (optional)",
      "1 1/2 cups water",
      "Salt, to taste"
    ],
    steps: [
      { text: "If using tougher greens, simmer them in water for 15 minutes until tender, then drain.", image: "https://i.pinimg.com/736x/e7/c2/c2/e7c2c2a1db220b897ea7a8dcd59c19df.jpg", alt: "" },
      { text: "Heat the oil in a pot and sauté the onion, garlic, and tomato until softened, about 5 minutes.", image: "https://cookingwithclaudy.com/wp-content/uploads/2025/08/Cassava-leaf-stew1-1040x1536.jpg", alt: "" },
      { text: "Whisk the peanut butter with the water until smooth, then stir it into the pot.", image: "https://i.pinimg.com/736x/22/43/5c/22435c6eed1ee13119866c9fe21266a9.jpg", alt: "" },
      { text: "Add the greens and eggplant, if using, along with the stock cube and chili.", image: "", alt: "" },
      { text: "Simmer for 15 to 20 minutes, stirring occasionally, until the sauce thickens and coats the greens.", image: "https://cookingwithclaudy.com/wp-content/uploads/2023/11/20231103113714_IMG_6436.jpg", alt: "" },
      { text: "Season with salt and serve with rice, fufu, or plantain.", image: "https://cookingwithclaudy.com/wp-content/uploads/2023/11/20231103121607_IMG_6445.jpg", alt: "" }
    ],
    tags: ["plant-based", "gluten-free", "stew"]
  },
  {
    id: "chakalaka",
    title: "Chakalaka (Spicy Vegetable Relish)",
    image: "https://i.pinimg.com/1200x/9b/33/bc/9b33bc56c07669df9ecbc1be792f0ef6.jpg",
    alt: "A bowl of chakalaka — a chunky relish of peppers, carrots, and beans in a spiced tomato base",
    cuisine: "Southern African",
    mealType: "Lunch",
    diet: "Vegan",
    prepTime: 25,
    difficulty: "Easy",
    calories: 210,
    servings: 4,
    description: "A South African vegetable relish, traditionally served alongside pap or bread. Quick to make and gets better as leftovers.",
    ingredients: [
      "2 tbsp cooking oil",
      "1 onion, diced",
      "2 cloves garlic, minced",
      "1 red bell pepper, diced",
      "1 green bell pepper, diced",
      "2 carrots, grated",
      "1 can (14 oz) diced tomatoes",
      "1 can (15 oz) beans (kidney or baked beans), drained and rinsed",
      "1 tsp curry powder",
      "1/2 tsp paprika",
      "1 chili, minced (optional)",
      "Salt, to taste"
    ],
    steps: [
      { text: "Heat the oil in a pan and sauté the onion and garlic until soft, about 4 minutes.", image: "https://i.pinimg.com/1200x/9a/79/ab/9a79ab0422b065b52e4c9d6201320e8d.jpg", alt: "" },
      { text: "Add the bell peppers and carrots and cook for 5 minutes until slightly softened.", image: "https://i.pinimg.com/1200x/9a/79/ab/9a79ab0422b065b52e4c9d6201320e8d.jpg", alt: "" },
      { text: "Stir in the diced tomatoes, curry powder, paprika, and chili, and simmer for 10 minutes.", image: "https://i.pinimg.com/1200x/9a/79/ab/9a79ab0422b065b52e4c9d6201320e8d.jpg", alt: "" },
      { text: "Add the beans and simmer for another 5 to 10 minutes until thickened.", image: "https://i.pinimg.com/1200x/6f/99/c7/6f99c7c3f8609d8f831a6cc5f7d090b7.jpg", alt: "" },
      { text: "Season with salt and serve warm or at room temperature as a side.", image: "https://i.pinimg.com/1200x/87/7d/5d/877d5d17cbe1ff1370180a31d00fa3a2.jpg", alt: "" }
    ],
    tags: ["side-dish", "plant-based", "gluten-free"]
  }
];